name: Java CI

on:
  push:
    branches:
      - 'java-test'
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'  # Adjust the Java version as needed
        distribution: 'temurin'
        architecture: x64

    - name: Go to relevant directory
      run: cd ./java-101

    - name: Build with Gradle
      run: ./gradlew build  # Use 'mvn install' if maven

    - name: Run tests
      run: ./gradlew test
