name: Github comment

on:
  push:
    branches:
      - main # the name of your main branch
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      issues: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: npm
          cache-dependency-path: .github/actions-scripts/package-lock.json

      - name: Install dependencies
        run: npm install
        working-directory: .github/actions-scripts/

      - name: Run script
        run: |
          node .github/actions-scripts/index.mjs
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
