name: Maven test run

on:
  push:
    branches:
      - main # the name of your main branch
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'  # Adjust the Java version as needed
        distribution: 'temurin'
        architecture: x64

    - name: Build with Gradle
      run: cd ./maven-project && mvn install  # Use 'gradle build' if gradle

    - name: Run tests
      run: cd ./maven-project && mvn test
